# Form implementation generated from reading ui file 'add_category.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addcategory(object):
    def setupUi(self, addcategory, TransWindow):
        addcategory.setObjectName("addcategory")
        addcategory.resize(234, 87)
        self.le_categoryname = QtWidgets.QLineEdit(addcategory)
        self.le_categoryname.setGeometry(QtCore.QRect(80, 20, 113, 22))
        self.le_categoryname.setObjectName("le_categoryname")
        self.pushButton = QtWidgets.QPushButton(addcategory)
        self.pushButton.setGeometry(QtCore.QRect(60, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(addcategory)
        self.label.setGeometry(QtCore.QRect(10, 20, 55, 21))
        self.label.setObjectName("label")

        self.retranslateUi(addcategory)
        QtCore.QMetaObject.connectSlotsByName(addcategory)

    def retranslateUi(self, addcategory):
        _translate = QtCore.QCoreApplication.translate
        addcategory.setWindowTitle(_translate("addcategory", "Add Category"))
        self.pushButton.setText(_translate("addcategory", "Add"))
        self.label.setText(_translate("addcategory", "Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addcategory = QtWidgets.QWidget()
    ui = Ui_addcategory()
    ui.setupUi(addcategory)
    addcategory.show()
    sys.exit(app.exec())
