# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Graph(object):
    def setupUi(self, Graph, AccForm):
        Graph.setObjectName("Graph")
        Graph.resize(677, 399)
        self.widget = QtWidgets.QWidget(Graph)
        self.widget.setGeometry(QtCore.QRect(450, 360, 195, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_dates = QtWidgets.QPushButton(self.widget)
        self.pb_dates.setObjectName("pb_dates")
        self.horizontalLayout.addWidget(self.pb_dates)
        self.pb_types = QtWidgets.QPushButton(self.widget)
        self.pb_types.setObjectName("pb_types")
        self.horizontalLayout.addWidget(self.pb_types)

        self.retranslateUi(Graph)
        QtCore.QMetaObject.connectSlotsByName(Graph)

    def retranslateUi(self, Graph):
        _translate = QtCore.QCoreApplication.translate
        Graph.setWindowTitle(_translate("Graph", "Form"))
        self.pb_dates.setText(_translate("Graph", "Sort by date"))
        self.pb_types.setText(_translate("Graph", "Sort by type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graph = QtWidgets.QWidget()
    ui = Ui_Graph()
    ui.setupUi(Graph)
    Graph.show()
    sys.exit(app.exec())
