# Form implementation generated from reading ui file 'accountinfo.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form, AccWindow):
        Form.setObjectName("Form")
        Form.resize(336, 178)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 30, 55, 16))
        self.label.setObjectName("label")
        self.l_iban = QtWidgets.QLabel(Form)
        self.l_iban.setGeometry(QtCore.QRect(90, 30, 211, 16))
        self.l_iban.setText("")
        self.l_iban.setObjectName("l_iban")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.label_3.setObjectName("label_3")
        self.l_accountid = QtWidgets.QLabel(Form)
        self.l_accountid.setGeometry(QtCore.QRect(140, 90, 55, 16))
        self.l_accountid.setText("")
        self.l_accountid.setObjectName("l_accountid")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Account Info"))
        self.label.setText(_translate("Form", "IBAN:"))
        self.label_3.setText(_translate("Form", "AccountID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
