# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 178)
        Form.setStyleSheet("background-color: #adb5bd")
        self.pb_add = QtWidgets.QPushButton(Form)
        self.pb_add.setGeometry(QtCore.QRect(30, 130, 93, 28))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.pb_add.setFont(font)
        self.pb_add.setStyleSheet("background-color:#228be6;\n"
"color: #fff\n"
"")
        self.pb_add.setObjectName("pb_add")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 90, 201, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_budget = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.label_budget.setFont(font)
        self.label_budget.setObjectName("label_budget")
        self.horizontalLayout_2.addWidget(self.label_budget)
        self.le_budgetname = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_budgetname.setStyleSheet("background-color : #fff")
        self.le_budgetname.setObjectName("le_budgetname")
        self.horizontalLayout_2.addWidget(self.le_budgetname)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 50, 271, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_accountname = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.label_accountname.setFont(font)
        self.label_accountname.setObjectName("label_accountname")
        self.horizontalLayout.addWidget(self.label_accountname)
        self.le_accountname = QtWidgets.QLineEdit(self.layoutWidget1)
        self.le_accountname.setStyleSheet("background-color : #fff\n"
"")
        self.le_accountname.setObjectName("le_accountname")
        self.horizontalLayout.addWidget(self.le_accountname)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Account add"))
        self.pb_add.setText(_translate("Form", "Add"))
        self.label_budget.setText(_translate("Form", "Budget"))
        self.le_budgetname.setPlaceholderText(_translate("Form", "Enter budget"))
        self.label_accountname.setText(_translate("Form", "Account name"))
        self.le_accountname.setPlaceholderText(_translate("Form", "Enter name of account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
