# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
# flake8: noqa
# pylint: skip-file

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(509, 407)
        Form.setStyleSheet("background-color: rgb(35,35,35)")
        self.pb_add = QtWidgets.QPushButton(Form)
        self.pb_add.setGeometry(QtCore.QRect(220, 340, 93, 28))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.pb_add.setFont(font)
        self.pb_add.setStyleSheet("background-color:#228be6;\n"
"color: #fff\n"
"")
        self.pb_add.setObjectName("pb_add")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(90, 70, 321, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_accountname = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.label_accountname.setFont(font)
        self.label_accountname.setStyleSheet("color : #fff;")
        self.label_accountname.setObjectName("label_accountname")
        self.horizontalLayout.addWidget(self.label_accountname)
        self.cb_accountnames = QtWidgets.QComboBox(self.widget)
        self.cb_accountnames.setStyleSheet("background-color : #fff;\n"
"border : no-border;")
        self.cb_accountnames.setObjectName("cb_accountnames")
        self.cb_accountnames.addItem("")
        self.cb_accountnames.addItem("")
        self.cb_accountnames.addItem("")
        self.cb_accountnames.addItem("")
        self.horizontalLayout.addWidget(self.cb_accountnames)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_budget = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.label_budget.setFont(font)
        self.label_budget.setStyleSheet("color : #fff;")
        self.label_budget.setObjectName("label_budget")
        self.horizontalLayout_2.addWidget(self.label_budget)
        self.le_budgetname = QtWidgets.QLineEdit(self.widget)
        self.le_budgetname.setStyleSheet("background-color : #fff")
        self.le_budgetname.setObjectName("le_budgetname")
        self.horizontalLayout_2.addWidget(self.le_budgetname)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l_currency = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.l_currency.setFont(font)
        self.l_currency.setStyleSheet("color : #fff")
        self.l_currency.setObjectName("l_currency")
        self.horizontalLayout_3.addWidget(self.l_currency)
        self.cb_currency = QtWidgets.QComboBox(self.widget)
        self.cb_currency.setStyleSheet("background-color : #fff;\n"
"border : no-border;")
        self.cb_currency.setObjectName("cb_currency")
        self.cb_currency.addItem("")
        self.cb_currency.addItem("")
        self.cb_currency.addItem("")
        self.cb_currency.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_currency)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Account add"))
        self.pb_add.setText(_translate("Form", "Add"))
        self.label_accountname.setText(_translate("Form", "Account type"))
        self.cb_accountnames.setItemText(0, _translate("Form", "Current"))
        self.cb_accountnames.setItemText(1, _translate("Form", "Savings"))
        self.cb_accountnames.setItemText(2, _translate("Form", "Business"))
        self.cb_accountnames.setItemText(3, _translate("Form", "Investment"))
        self.label_budget.setText(_translate("Form", "Budget"))
        self.le_budgetname.setPlaceholderText(_translate("Form", "Enter budget"))
        self.l_currency.setText(_translate("Form", "Currency"))
        self.cb_currency.setItemText(0, _translate("Form", "RON"))
        self.cb_currency.setItemText(1, _translate("Form", "EUR"))
        self.cb_currency.setItemText(2, _translate("Form", "GBP"))
        self.cb_currency.setItemText(3, _translate("Form", "USD"))
