# Form implementation generated from reading ui file 'transfer.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_createtransfer(object):
    def setupUi(self, createtransfer, Account):
        createtransfer.setObjectName("createtransfer")
        createtransfer.resize(400, 300)
        self.le_iban = QtWidgets.QLineEdit(createtransfer)
        self.le_iban.setGeometry(QtCore.QRect(130, 60, 181, 22))
        self.le_iban.setObjectName("le_iban")
        self.pb_createtransfer = QtWidgets.QPushButton(createtransfer)
        self.pb_createtransfer.setGeometry(QtCore.QRect(40, 250, 131, 28))
        self.pb_createtransfer.setObjectName("pb_createtransfer")
        self.l_iban = QtWidgets.QLabel(createtransfer)
        self.l_iban.setGeometry(QtCore.QRect(40, 60, 55, 16))
        self.l_iban.setObjectName("l_iban")
        self.l_value = QtWidgets.QLabel(createtransfer)
        self.l_value.setGeometry(QtCore.QRect(40, 100, 55, 16))
        self.l_value.setObjectName("l_value")
        self.le_value = QtWidgets.QLineEdit(createtransfer)
        self.le_value.setGeometry(QtCore.QRect(130, 100, 113, 22))
        self.le_value.setObjectName("le_value")
        self.l_description = QtWidgets.QLabel(createtransfer)
        self.l_description.setGeometry(QtCore.QRect(40, 150, 81, 16))
        self.l_description.setObjectName("l_description")
        self.le_description = QtWidgets.QLineEdit(createtransfer)
        self.le_description.setGeometry(QtCore.QRect(140, 150, 191, 61))
        self.le_description.setObjectName("le_description")

        self.retranslateUi(createtransfer)
        QtCore.QMetaObject.connectSlotsByName(createtransfer)

    def retranslateUi(self, createtransfer):
        _translate = QtCore.QCoreApplication.translate
        createtransfer.setWindowTitle(_translate("createtransfer", "Form"))
        self.pb_createtransfer.setText(_translate("createtransfer", "Create Transfer"))
        self.l_iban.setText(_translate("createtransfer", "IBAN"))
        self.l_value.setText(_translate("createtransfer", "VALUE"))
        self.l_description.setText(_translate("createtransfer", "DESCRIPTION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createtransfer = QtWidgets.QWidget()
    ui = Ui_createtransfer()
    ui.setupUi(createtransfer)
    createtransfer.show()
    sys.exit(app.exec())
