# Form implementation generated from reading ui file 'testt.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFrame

class Ui_TransactionFrame(QFrame):
    def __init__(self, parent):
        QFrame.__init__(self)
        self.setObjectName("TransactionFrame")
        self.resize(936, 478)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.setFont(font)
        self.setStyleSheet("background-color: rgb(35,35,35)")
        self.pb_addtransaction = QtWidgets.QPushButton(self)
        self.pb_addtransaction.setGeometry(QtCore.QRect(340, 310, 221, 32))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.pb_addtransaction.setFont(font)
        self.pb_addtransaction.setStyleSheet("background-color:#228be6;\n"
"color: #fff\n"
"")
        self.pb_addtransaction.setObjectName("pb_addtransaction")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(310, 100, 281, 141))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 19, 2)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_nume = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.l_nume.setFont(font)
        self.l_nume.setStyleSheet("color : #fff;")
        self.l_nume.setObjectName("l_nume")
        self.verticalLayout.addWidget(self.l_nume)
        self.l_value = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.l_value.setFont(font)
        self.l_value.setStyleSheet("color : #fff;")
        self.l_value.setObjectName("l_value")
        self.verticalLayout.addWidget(self.l_value)
        self.l_value_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.l_value_2.setFont(font)
        self.l_value_2.setStyleSheet("color : #fff;")
        self.l_value_2.setObjectName("l_value_2")
        self.verticalLayout.addWidget(self.l_value_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_nume = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_nume.sizePolicy().hasHeightForWidth())
        self.le_nume.setSizePolicy(sizePolicy)
        self.le_nume.setStyleSheet("background-color : #fff\n"
"")
        self.le_nume.setText("")
        self.le_nume.setObjectName("le_nume")
        self.verticalLayout_2.addWidget(self.le_nume)
        self.le_value = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_value.sizePolicy().hasHeightForWidth())
        self.le_value.setSizePolicy(sizePolicy)
        self.le_value.setStyleSheet("background-color : #fff")
        self.le_value.setObjectName("le_value")
        self.verticalLayout_2.addWidget(self.le_value)
        self.cb_typeoftacc = QtWidgets.QComboBox(self.widget)
        self.cb_typeoftacc.setStyleSheet("background-color: #fff")
        self.cb_typeoftacc.setObjectName("cb_typeoftacc")
        self.verticalLayout_2.addWidget(self.cb_typeoftacc)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)


    def retranslateUi(self, TransactionFrame):
        _translate = QtCore.QCoreApplication.translate
        TransactionFrame.setWindowTitle(_translate("TransactionFrame", "Frame"))
        self.pb_addtransaction.setText(_translate("TransactionFrame", "Add transaction"))
        self.l_nume.setText(_translate("TransactionFrame", "Name"))
        self.l_value.setText(_translate("TransactionFrame", "Value"))
        self.l_value_2.setText(_translate("TransactionFrame", "Type"))
        self.le_nume.setPlaceholderText(_translate("TransactionFrame", "Transaction name"))
        self.le_value.setPlaceholderText(_translate("TransactionFrame", "Enter budget"))


